### ISSUE TITLE
is the character "."  not handled correct when use geras with thanos_remote_read?

### ISSUE THREAD

**Issue by Jamlee** [G-Research/thanos-remote-read#10]
i get the error like below:
![image](https://user-images.githubusercontent.com/5196641/82645522-9124b580-9c45-11ea-875c-8bd9988be861.png)

there are my docker-compose.yml
![image](https://user-images.githubusercontent.com/5196641/82645579-ae598400-9c45-11ea-8fde-a2707675bddd.png)

**Comment by dgl** [comment]
We've provided a fix for this on the Geras side: https://github.com/G-Research/geras/pull/80
