### ISSUE TITLE
remote_read returns 500 Internal Server Error

### ISSUE THREAD

**Issue by rastislavs** [G-Research/thanos-remote-read#22]
I started a `thanos-remote-read` instance and pointed it to `thanos-query`. Configured a Prometheus instance with:

```
remote_read:
- url: http://<thanos-remote-read-IP>:10080/api/v1/read
```

Upon a query, Prometheus is returning:
```
remote_read: remote server http://<thanos-remote-read-IP>:10080/api/v1/read returned HTTP status 500 Internal Server Error: rpc error: code = Unavailable desc = connection closed
```

In the logs of `thanos-query` I only see a lot of info messages like:
```
ts=2021-06-09T15:27:08.789865354Z caller=main.go:278 level=info traceID=00000000000000000000000000000000 msg="thanos request" request="min_time:1623230828556 max_time:1623252428556 matchers:<name:\"app\" value:\"node-exporter\" > matchers:<type:RE name:\"fstype\" value:\"ext.|xfs\" > matchers:<name:\"__name__\" value:\"node_filesystem_files_free\" > aggregates:RAW "
```

Am I doing something wrong? How can I debug the issue?

**Comment by dgl** [comment]
Can you confirm the port your thanos-query listens on and which port you pointed thanos-remote-read at?

At a guess you may have pointed thanos-remote-read at the HTTP rather than the gRPC port...

**Comment by rastislavs** [comment]
Right, my mistake - wrong port indeed. Thanks!

**Comment by brijeshvp** [comment]
@dgl i'm facing this issue. my thanos-store runs on 0.0.0.0:10901 (grpc endpoint) and i've pointed thanos-remote-read like: `thanos-remote-read -store "0.0.0.0:10901"` i am migrating thanos data stored in s3 bucket to victoriaMetrics using command `vmctl-darwin-arm64 remote-read \
--remote-read-src-addr=http://127.0.0.1:10080  --remote-read-filter-time-start=2024-06-01T00:00:00Z  \
--remote-read-step-interval=day \
--vm-addr=http://127.0.0.1:8480 \
--vm-concurrency=3 --remote-read-concurrency=3 --remote-read-http-timeout=60m --remote-read-insecure-skip-verify=true --vm-insecure-skip-verify=true --vm-account-id=0 --verbose`

i am running thanos-remote-read in local and vm-addr is kubernetes service which port-forwarded. on running this command, thanos-store is getting OOMKilled with status 500 and pod gets restarted. 

Any help is highly appreciated. Thanks!

**Comment by dgl** [comment]
@brijeshvp the thanos-remote-read logs should show you the query VM is making. My guess is `--remote-read-step-interval=day` is trying to load (all?) your data for a day, which I suspect your thanos-store isn't sized for. Try loading less data? (If not, please open a new issue with the logs from thanos-remote-read rather than replying on an unrelated issue.)
