### ISSUE TITLE
building described in readme not working for new go versions

### ISSUE THREAD

**Issue by kelvan** [G-Research/thanos-remote-read#29]
Tried to run go get as described in the readme, but it fails:

```
go get github.com/G-Research/thanos-remote-read

go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
```

`go install github.com/G-Research/thanos-remote-read@latest` works

go version go1.18 linux/amd64

**Comment by dgl** [comment]
Thanks for spotting; this is a general problem with Go, see https://utcc.utoronto.ca/~cks/space/blog/programming/GoAndDeprecatingGoGet for some commentary. Will update the readme as this needs >=1.17 now (sadly there's not a single backwards compatible command that also works on Go versions older than 1.16).
