### ISSUE TITLE
not support != when used with geras

### ISSUE THREAD

**Issue by Jamlee** [G-Research/thanos-remote-read#9]
Is Work:
`node_filesystem_avail_bytes{job="node-exporter", fstype=~".+"}`

Is not Work
`node_filesystem_avail_bytes{job="node-exporter", fstype!=""}`

**Comment by dgl** [comment]
Is there an error? There are some limitations in Geras on what it can convert to OpenTSDB queries, although most of this should work on recent versions of Geras.

Also I'd strongly recommend a setup like mentioned on:
https://github.com/G-Research/thanos-remote-read/blob/master/docs/ruler.md, i.e. using `required_matchers` to avoid sending every single Prometheus query to the remote read as well.
